name: ${project.name}
version: ${project.version}-b${env.TRAVIS_BUILD_NUMBER}
description: ${project.description}
authors: [cereal, Sleaker, mung3r]
website: ${project.url}
api-version: 1.13

main: ${mainClass}
load: startup